### ISSUE TITLE
Endurance curve

### ISSUE THREAD

**Issue by LolloCappo** [Gunnstein/fatpack#4]
Can you please provide a reference and theoretical explanations for the endurance curve definition? It is not that clear to me the usage of Sc on the definitions.
Thanks

**Comment by Gunnstein** [comment]
Please check out my answer to issue #1 for some references to endurance curve definitions.

An endurance curve  (also known as a SN curve) defines the fatigue resistance of a structural detail and is determined by the material properties and the stress distribution due to loading and local geometry in the structural detail. Sc (detail category) is one of the parameters that is used to define an endurance curve, a small Sc means low fatigue resistance and a high Sc means high fatigue resistance. 

For an concrete example of what Sc is: see figure 7.1 on page 17 in [Eurocode 3](https://www.phd.eng.br/wp-content/uploads/2015/12/en.1993.1.9.2005-1.pdf), which shows different endurance curves from Sc=36MPa to 160MPa. 

In practical use, where you have to determine the fatigue life of a structural detail, you would first find the relevant structural detail in the second column of table 8. The detail category (and also endurance curve/fatigue resistance) of that structural component is then found in the first column of the corresponding row.

**Comment by LolloCappo** [comment]
Thank you very much for the explanation and the details!
