### ISSUE TITLE
Error in Rainflow bins

### ISSUE THREAD

**Issue by abhijeet-pandey** [Gunnstein/fatpack#9]
I noticed an error in the find_rainflow_matrix bin creation step, I assume below should be cc[:, 0].max instead?
![image](https://user-images.githubusercontent.com/24558167/145346858-491f3cc6-1581-4fda-8f63-f4843403e056.png)

**Comment by Gunnstein** [comment]
Dear @abhijeet-pandey,

Is this from find_rainflow_matrix in rainflow.py? 

I believe this was fixed in #7 and that the current repository/version has the correct index, see image below.

![image](https://user-images.githubusercontent.com/8481663/145387908-9840a59d-d6be-4b36-80a9-051be7a615cd.png)

Best regards,
Gunnstein

**Comment by abhijeet-pandey** [comment]
Somehow pip install only installed the older version for me I guess.
Cheers!
